//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCert.FAP_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        private bool GenderField;
        
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcademicEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RollNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EthnicityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AcademicEmail {
            get {
                return this.AcademicEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AcademicEmailField, value) != true)) {
                    this.AcademicEmailField = value;
                    this.RaisePropertyChanged("AcademicEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RollNumber {
            get {
                return this.RollNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RollNumberField, value) != true)) {
                    this.RollNumberField = value;
                    this.RaisePropertyChanged("RollNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MemberCode {
            get {
                return this.MemberCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberCodeField, value) != true)) {
                    this.MemberCodeField = value;
                    this.RaisePropertyChanged("MemberCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Ethnicity {
            get {
                return this.EthnicityField;
            }
            set {
                if ((object.ReferenceEquals(this.EthnicityField, value) != true)) {
                    this.EthnicityField = value;
                    this.RaisePropertyChanged("Ethnicity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentFullNameField;
        
        private float MarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Semester {
            get {
                return this.SemesterField;
            }
            set {
                if ((object.ReferenceEquals(this.SemesterField, value) != true)) {
                    this.SemesterField = value;
                    this.RaisePropertyChanged("Semester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubjectCode {
            get {
                return this.SubjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectCodeField, value) != true)) {
                    this.SubjectCodeField = value;
                    this.RaisePropertyChanged("SubjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubjectName {
            get {
                return this.SubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectNameField, value) != true)) {
                    this.SubjectNameField = value;
                    this.RaisePropertyChanged("SubjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StudentFullName {
            get {
                return this.StudentFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentFullNameField, value) != true)) {
                    this.StudentFullNameField = value;
                    this.RaisePropertyChanged("StudentFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((this.MarkField.Equals(value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FAP_Service.UserWebServiceSoap")]
    public interface UserWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name academicEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByAcademicEmail", ReplyAction="*")]
        eCert.FAP_Service.GetUserByAcademicEmailResponse GetUserByAcademicEmail(eCert.FAP_Service.GetUserByAcademicEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByAcademicEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetUserByAcademicEmailResponse> GetUserByAcademicEmailAsync(eCert.FAP_Service.GetUserByAcademicEmailRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByRollNumber", ReplyAction="*")]
        eCert.FAP_Service.GetUserByRollNumberResponse GetUserByRollNumber(eCert.FAP_Service.GetUserByRollNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByRollNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetUserByRollNumberResponse> GetUserByRollNumberAsync(eCert.FAP_Service.GetUserByRollNumberRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPassedSubjects", ReplyAction="*")]
        eCert.FAP_Service.GetPassedSubjectsResponse GetPassedSubjects(eCert.FAP_Service.GetPassedSubjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPassedSubjects", ReplyAction="*")]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetPassedSubjectsResponse> GetPassedSubjectsAsync(eCert.FAP_Service.GetPassedSubjectsRequest request);
        
        // CODEGEN: Generating message contract since element name rollnumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetailPassedSubject", ReplyAction="*")]
        eCert.FAP_Service.GetDetailPassedSubjectResponse GetDetailPassedSubject(eCert.FAP_Service.GetDetailPassedSubjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetailPassedSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetDetailPassedSubjectResponse> GetDetailPassedSubjectAsync(eCert.FAP_Service.GetDetailPassedSubjectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByAcademicEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByAcademicEmail", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetUserByAcademicEmailRequestBody Body;
        
        public GetUserByAcademicEmailRequest() {
        }
        
        public GetUserByAcademicEmailRequest(eCert.FAP_Service.GetUserByAcademicEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByAcademicEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string academicEmail;
        
        public GetUserByAcademicEmailRequestBody() {
        }
        
        public GetUserByAcademicEmailRequestBody(string academicEmail) {
            this.academicEmail = academicEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByAcademicEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByAcademicEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetUserByAcademicEmailResponseBody Body;
        
        public GetUserByAcademicEmailResponse() {
        }
        
        public GetUserByAcademicEmailResponse(eCert.FAP_Service.GetUserByAcademicEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByAcademicEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eCert.FAP_Service.User GetUserByAcademicEmailResult;
        
        public GetUserByAcademicEmailResponseBody() {
        }
        
        public GetUserByAcademicEmailResponseBody(eCert.FAP_Service.User GetUserByAcademicEmailResult) {
            this.GetUserByAcademicEmailResult = GetUserByAcademicEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByRollNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByRollNumber", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetUserByRollNumberRequestBody Body;
        
        public GetUserByRollNumberRequest() {
        }
        
        public GetUserByRollNumberRequest(eCert.FAP_Service.GetUserByRollNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByRollNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        public GetUserByRollNumberRequestBody() {
        }
        
        public GetUserByRollNumberRequestBody(string rollNumber) {
            this.rollNumber = rollNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByRollNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByRollNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetUserByRollNumberResponseBody Body;
        
        public GetUserByRollNumberResponse() {
        }
        
        public GetUserByRollNumberResponse(eCert.FAP_Service.GetUserByRollNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByRollNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eCert.FAP_Service.User GetUserByRollNumberResult;
        
        public GetUserByRollNumberResponseBody() {
        }
        
        public GetUserByRollNumberResponseBody(eCert.FAP_Service.User GetUserByRollNumberResult) {
            this.GetUserByRollNumberResult = GetUserByRollNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPassedSubjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPassedSubjects", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetPassedSubjectsRequestBody Body;
        
        public GetPassedSubjectsRequest() {
        }
        
        public GetPassedSubjectsRequest(eCert.FAP_Service.GetPassedSubjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPassedSubjectsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        public GetPassedSubjectsRequestBody() {
        }
        
        public GetPassedSubjectsRequestBody(string rollNumber) {
            this.rollNumber = rollNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPassedSubjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPassedSubjectsResponse", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetPassedSubjectsResponseBody Body;
        
        public GetPassedSubjectsResponse() {
        }
        
        public GetPassedSubjectsResponse(eCert.FAP_Service.GetPassedSubjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPassedSubjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eCert.FAP_Service.Subject[] GetPassedSubjectsResult;
        
        public GetPassedSubjectsResponseBody() {
        }
        
        public GetPassedSubjectsResponseBody(eCert.FAP_Service.Subject[] GetPassedSubjectsResult) {
            this.GetPassedSubjectsResult = GetPassedSubjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailPassedSubjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailPassedSubject", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetDetailPassedSubjectRequestBody Body;
        
        public GetDetailPassedSubjectRequest() {
        }
        
        public GetDetailPassedSubjectRequest(eCert.FAP_Service.GetDetailPassedSubjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDetailPassedSubjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subjectCode;
        
        public GetDetailPassedSubjectRequestBody() {
        }
        
        public GetDetailPassedSubjectRequestBody(string rollnumber, string subjectCode) {
            this.rollnumber = rollnumber;
            this.subjectCode = subjectCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailPassedSubjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailPassedSubjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public eCert.FAP_Service.GetDetailPassedSubjectResponseBody Body;
        
        public GetDetailPassedSubjectResponse() {
        }
        
        public GetDetailPassedSubjectResponse(eCert.FAP_Service.GetDetailPassedSubjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDetailPassedSubjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eCert.FAP_Service.Subject GetDetailPassedSubjectResult;
        
        public GetDetailPassedSubjectResponseBody() {
        }
        
        public GetDetailPassedSubjectResponseBody(eCert.FAP_Service.Subject GetDetailPassedSubjectResult) {
            this.GetDetailPassedSubjectResult = GetDetailPassedSubjectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserWebServiceSoapChannel : eCert.FAP_Service.UserWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWebServiceSoapClient : System.ServiceModel.ClientBase<eCert.FAP_Service.UserWebServiceSoap>, eCert.FAP_Service.UserWebServiceSoap {
        
        public UserWebServiceSoapClient() {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eCert.FAP_Service.GetUserByAcademicEmailResponse eCert.FAP_Service.UserWebServiceSoap.GetUserByAcademicEmail(eCert.FAP_Service.GetUserByAcademicEmailRequest request) {
            return base.Channel.GetUserByAcademicEmail(request);
        }
        
        public eCert.FAP_Service.User GetUserByAcademicEmail(string academicEmail) {
            eCert.FAP_Service.GetUserByAcademicEmailRequest inValue = new eCert.FAP_Service.GetUserByAcademicEmailRequest();
            inValue.Body = new eCert.FAP_Service.GetUserByAcademicEmailRequestBody();
            inValue.Body.academicEmail = academicEmail;
            eCert.FAP_Service.GetUserByAcademicEmailResponse retVal = ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetUserByAcademicEmail(inValue);
            return retVal.Body.GetUserByAcademicEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetUserByAcademicEmailResponse> eCert.FAP_Service.UserWebServiceSoap.GetUserByAcademicEmailAsync(eCert.FAP_Service.GetUserByAcademicEmailRequest request) {
            return base.Channel.GetUserByAcademicEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<eCert.FAP_Service.GetUserByAcademicEmailResponse> GetUserByAcademicEmailAsync(string academicEmail) {
            eCert.FAP_Service.GetUserByAcademicEmailRequest inValue = new eCert.FAP_Service.GetUserByAcademicEmailRequest();
            inValue.Body = new eCert.FAP_Service.GetUserByAcademicEmailRequestBody();
            inValue.Body.academicEmail = academicEmail;
            return ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetUserByAcademicEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eCert.FAP_Service.GetUserByRollNumberResponse eCert.FAP_Service.UserWebServiceSoap.GetUserByRollNumber(eCert.FAP_Service.GetUserByRollNumberRequest request) {
            return base.Channel.GetUserByRollNumber(request);
        }
        
        public eCert.FAP_Service.User GetUserByRollNumber(string rollNumber) {
            eCert.FAP_Service.GetUserByRollNumberRequest inValue = new eCert.FAP_Service.GetUserByRollNumberRequest();
            inValue.Body = new eCert.FAP_Service.GetUserByRollNumberRequestBody();
            inValue.Body.rollNumber = rollNumber;
            eCert.FAP_Service.GetUserByRollNumberResponse retVal = ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetUserByRollNumber(inValue);
            return retVal.Body.GetUserByRollNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetUserByRollNumberResponse> eCert.FAP_Service.UserWebServiceSoap.GetUserByRollNumberAsync(eCert.FAP_Service.GetUserByRollNumberRequest request) {
            return base.Channel.GetUserByRollNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<eCert.FAP_Service.GetUserByRollNumberResponse> GetUserByRollNumberAsync(string rollNumber) {
            eCert.FAP_Service.GetUserByRollNumberRequest inValue = new eCert.FAP_Service.GetUserByRollNumberRequest();
            inValue.Body = new eCert.FAP_Service.GetUserByRollNumberRequestBody();
            inValue.Body.rollNumber = rollNumber;
            return ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetUserByRollNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eCert.FAP_Service.GetPassedSubjectsResponse eCert.FAP_Service.UserWebServiceSoap.GetPassedSubjects(eCert.FAP_Service.GetPassedSubjectsRequest request) {
            return base.Channel.GetPassedSubjects(request);
        }
        
        public eCert.FAP_Service.Subject[] GetPassedSubjects(string rollNumber) {
            eCert.FAP_Service.GetPassedSubjectsRequest inValue = new eCert.FAP_Service.GetPassedSubjectsRequest();
            inValue.Body = new eCert.FAP_Service.GetPassedSubjectsRequestBody();
            inValue.Body.rollNumber = rollNumber;
            eCert.FAP_Service.GetPassedSubjectsResponse retVal = ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetPassedSubjects(inValue);
            return retVal.Body.GetPassedSubjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetPassedSubjectsResponse> eCert.FAP_Service.UserWebServiceSoap.GetPassedSubjectsAsync(eCert.FAP_Service.GetPassedSubjectsRequest request) {
            return base.Channel.GetPassedSubjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<eCert.FAP_Service.GetPassedSubjectsResponse> GetPassedSubjectsAsync(string rollNumber) {
            eCert.FAP_Service.GetPassedSubjectsRequest inValue = new eCert.FAP_Service.GetPassedSubjectsRequest();
            inValue.Body = new eCert.FAP_Service.GetPassedSubjectsRequestBody();
            inValue.Body.rollNumber = rollNumber;
            return ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetPassedSubjectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eCert.FAP_Service.GetDetailPassedSubjectResponse eCert.FAP_Service.UserWebServiceSoap.GetDetailPassedSubject(eCert.FAP_Service.GetDetailPassedSubjectRequest request) {
            return base.Channel.GetDetailPassedSubject(request);
        }
        
        public eCert.FAP_Service.Subject GetDetailPassedSubject(string rollnumber, string subjectCode) {
            eCert.FAP_Service.GetDetailPassedSubjectRequest inValue = new eCert.FAP_Service.GetDetailPassedSubjectRequest();
            inValue.Body = new eCert.FAP_Service.GetDetailPassedSubjectRequestBody();
            inValue.Body.rollnumber = rollnumber;
            inValue.Body.subjectCode = subjectCode;
            eCert.FAP_Service.GetDetailPassedSubjectResponse retVal = ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetDetailPassedSubject(inValue);
            return retVal.Body.GetDetailPassedSubjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eCert.FAP_Service.GetDetailPassedSubjectResponse> eCert.FAP_Service.UserWebServiceSoap.GetDetailPassedSubjectAsync(eCert.FAP_Service.GetDetailPassedSubjectRequest request) {
            return base.Channel.GetDetailPassedSubjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<eCert.FAP_Service.GetDetailPassedSubjectResponse> GetDetailPassedSubjectAsync(string rollnumber, string subjectCode) {
            eCert.FAP_Service.GetDetailPassedSubjectRequest inValue = new eCert.FAP_Service.GetDetailPassedSubjectRequest();
            inValue.Body = new eCert.FAP_Service.GetDetailPassedSubjectRequestBody();
            inValue.Body.rollnumber = rollnumber;
            inValue.Body.subjectCode = subjectCode;
            return ((eCert.FAP_Service.UserWebServiceSoap)(this)).GetDetailPassedSubjectAsync(inValue);
        }
    }
}
